services:
  payment-db:
    image: postgres:16
    container_name: payment-db
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - payment_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d payment_db"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks: [ innowise-net ]

  payment-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payment-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://payment-db:5432/payment_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SERVER_PORT: 8085
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_LIQUIBASE_ENABLED: "true"
      SPRING_LIQUIBASE_CHANGE_LOG: classpath:db/changelog/db.changelog-master.yaml
    ports:
      - "8085:8085"
    depends_on:
      payment-db:
        condition: service_healthy
    networks: [ innowise-net ]

volumes:
  payment_db_data:

networks:
  innowise-net:
    external: true
