version: "3.8"

services:
  payment-mongo:
    image: mongo:7.0
    restart: unless-stopped
    volumes:
      - payment-mongo-data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval 'db.runCommand({ ping: 1 }).ok' localhost:27017/admin | grep 1"]
      interval: 5s
      timeout: 3s
      retries: 30

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    restart: unless-stopped
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"

      # только внутренняя сеть docker-compose
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  payment-service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      payment-mongo:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      SERVER_PORT: ${SERVER_PORT:-8085}
      SPRING_DATA_MONGODB_URI: ${SPRING_DATA_MONGODB_URI:-mongodb://payment-mongo:27017/payment_db}
      APP_LIQUIBASE_URL: "mongodb://payment-mongo:27017/payment_db"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:-kafka:9092}
      EXTERNAL_RANDOM_URL: ${EXTERNAL_RANDOM_URL:-https://www.randomnumberapi.com/api/v1.0/random?min=1&max=100&count=1}
    ports:
      - "8085:8085"

volumes:
  payment-mongo-data:
